### ISSUE TITLE
Really high percentages?

### ISSUE THREAD

**Issue by TRianR** [jogo9225/Gorder_CSCI2270_FinalProject#2]
When running the program, following the instructions on the read.me, I'm getting really high percentage values such as 91800% for "The largest percent change in the number of parts forecasted for a particular part number is:".  Is that correct?

**Comment by jogo9225** [comment]
This is occurring because it marks a change from 0 to a number > 0, which means that the percentage change is wonky.  We'll try to come up with a better algorithm.
