### ISSUE TITLE
rounding in C++

### ISSUE THREAD

**Issue by amirkashi** [jogo9225/Gorder_CSCI2270_FinalProject#3]
If you want to round numbers in C++
include iomanip library like:    #include <iomanip>
and then before the number you want to round add: setprecision(2) << fixed
following is and example for your code:
cout << "The average percent change in the forecast when the model did change is: " << setprecision(2) << fixed << avgChanged*100 << "%" << endl;
the value int he parenthesis (2 here) tells C++ how many  significant figures you want to print in the terminal.

**Comment by jogo9225** [comment]
Thanks! I'll implement that.
